<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.18</version>
        <relativePath/>
    </parent>
    <packaging>pom</packaging>

    <modules>
        <module>server-demo-app</module>
        <module>server-demo-client</module>
        <module>server-demo-common</module>
        <module>server-demo-domain</module>
        <module>server-demo-main</module>
        <module>server-demo-infra-api</module>
        <module>server-demo-infra-impl</module>
        <module>server-demo-test</module>
        <module>server-demo-web</module>
    </modules>

    <groupId>com.jd.tech.stack.study</groupId>
    <artifactId>server-demo</artifactId>
    <version>1.0.0</version>
    <name>server-demo</name>
    <description>服务端演示</description>
    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <mybatis.version>2.3.2</mybatis.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.jd.tech.stack.study</groupId>
                <artifactId>server-demo-app</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.jd.tech.stack.study</groupId>
                <artifactId>server-demo-client</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.jd.tech.stack.study</groupId>
                <artifactId>server-demo-common</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.jd.tech.stack.study</groupId>
                <artifactId>server-demo-domain</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.jd.tech.stack.study</groupId>
                <artifactId>server-demo-main</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.jd.tech.stack.study</groupId>
                <artifactId>server-demo-infra-api</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.jd.tech.stack.study</groupId>
                <artifactId>server-demo-infra-impl</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.jd.tech.stack.study</groupId>
                <artifactId>server-demo-test</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.jd.tech.stack.study</groupId>
                <artifactId>server-demo-web</artifactId>
                <version>1.0.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.9.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                    <parameters>true</parameters>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.30</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <useManifestOnlyJar>false</useManifestOnlyJar>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
